### ISSUE TITLE
Verify and Ensure Support for Node.js 20

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#1104]
### Motivation

LTS starts in October

**Comment by nedsalk** [comment]
I've tried using v20 in our codebase and got failing tests because fetching wasn't working properly. The culprit was `graphql-request` in the `providers` package which has the library `cross-fetch` as its dependency which, in turn, is using v2 of `node-fetch`, which doesn't have support for node v19 and v20 at the time of writing. The PR for adding this support is [this one](https://github.com/node-fetch/node-fetch/pull/1765). After it gets merged, I'll return to the issue and try again.

**Comment by pedronauck** [comment]
I also got this error when trying to install `fuels` using `node20`

![CleanShot 2023-10-24 at 19 26 03@2x](https://github.com/FuelLabs/fuels-ts/assets/2029172/ff55b59c-d434-4467-a6ab-a8afdaac0950)

**Comment by nedsalk** [comment]
Although the issue mentioned above is resolved, I'll wait for #1374 to merge before continuing on this as it's replacing `node-fetch` with the native fetch. We'd have to override the used `node-fetch` version to get the fix, so I'd just wait until it's completely removed.

**Comment by arboleya** [comment]
Closed in #1544
