### ISSUE TITLE
Bump major version of ethers from v5 to v6

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1133]
Currently the repo is using ethers v5.7 everywhere. Given that v6 has been around for some time, we should investigate and bump the major version.

**Comment by Dhaiwat10** [comment]
@nedsalk turns out we have `ethers` in our package.json but we aren't actually using it anywhere inside of the project. We are only using `@ethersproject/bytes` which is already up-to-date at 5.7, it doesn't have a newer version. Since `ethers` is an unused dependency, I have created a PR that purges it from the repo: https://github.com/FuelLabs/fuels-ts/pull/1168
