### ISSUE TITLE
Add a deployInstance method to contract factories & export contract bytecode through a separate file via typegen

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1150]
Follow-up from #1093:

To reduce & simplify the boilerplate required to deploy a contract after using typegen, adding a `deployInstance` method to the contract factories would be beneficial. This would take the boilerplate required to deploy a contract from this:

```ts
import bytecode from '../.../out/debug/bytecode.bin';

const factory = new ContractFactory(bytecode, FuelCounterAbi__factory.abi, wallet);
const instance = await factory.deployContract();
```

To this:

```ts
const instance = await FuelCounterAbi__factory.deployInstance(wallet);
```

We will need to include the contract's bytecode and storage slots in the generated factory to enable this.

Any thoughts? @FuelLabs/sdk-ts

**Comment by nedsalk** [comment]
Throwing in the idea of possibly adding an optional `bytecode` parameter to `deployInstance`:
```ts
FuelCounterAbi__factory.deployInstance = (wallet, bytecode = undefined) => {
const usedBytecode = bytecode ? hexlify(bytecode) : this.bytecode;
...
}
```
Because different contracts with different bytecode can implement the same abi.

A possibly better alternative to the one I mentioned above is to just explain to the users that, if they want to use a different bytecode than the one located in the folder `typegen` was run against, they can use the previous approach of 
```ts
import bytecode from '../.../out/debug/bytecode.bin';

const factory = new ContractFactory(bytecode, FuelCounterAbi__factory.abi, wallet);
const instance = await factory.deployContract();
```

As far as I'm concerned, 
```ts
const instance = await FuelCounterAbi__factory.deployInstance(wallet);
```
 makes sense with or without the optional `bytecode` parameter.

**Comment by arboleya** [comment]
Since `bytecode` is only needed for deploying, I'd make it a required argument in the `deployContract()` method.

```ts
const factory = new ContractFactory(FuelCounterAbi__factory.abi, wallet);
const instance = await factory.deployContract(bytecode);
```

In Typegen land, we can generate a Typescript file exporting the `hexlified` contract bytecode.

```ts
// MyContract.hex.ts
export default '0x000';
```

Users could then use it to call `deployContract`:

```ts
import hex from './types/MyContract.hex';

const factory = new ContractFactory(FuelCounterAbi__factory.abi, wallet);
const instance = await factory.deployContract(hex);
```

Bytecode should be imported manually to ensure they're not added by default.

We don't want web builds embedding _[hexlified]_ bytecode unnecessarily, even when tree-shaking.

> **Note** _The same is not valid for `Script` and `Predicate`, which rely on their bytecode to function_.

**Comment by Dhaiwat10** [comment]
Thanks for the input guys @arboleya @nedsalk! 

@arboleya What you mentioned around importing bytecode causing large web builds is very interesting, I was not aware of that. I'll keep this in mind.
