### ISSUE TITLE
Should accept Uint8Array as Array / data or bytes type

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1553]
It's a pain having to convert between all kinds of array / bytes types. We should consider a connonical way to encode/decode between data and accept common forms of data like Uint8Arrays.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1545

## Steps

- [x] Add runtime support for passing `Uint8Array` as `Vec<8>` (#2018)
- [ ] Add typegen support for passing `Uint8Array` as `Vec<u8>`
- [ ] ...more?

**Comment by danielbate** [comment]
I suspect this was resolved by the changes [here](https://github.com/FuelLabs/fuels-ts/pull/2018) and [here](https://github.com/FuelLabs/fuels-ts/pull/2289) as I can't see any other type that should accept bytes/array in this way, any thoughts @FuelLabs/sdk-ts?

**Comment by arboleya** [comment]
@danielbate Did you see [this comment](https://github.com/FuelLabs/fuels-ts/pull/2579#discussion_r1676332167)? It seems related.

**Comment by danielbate** [comment]
That seems related to typegen, re #2784

**Comment by arboleya** [comment]
@Dhaiwat10 Closed as not planned?

**Comment by Dhaiwat10** [comment]
@arboleya I closed this via Linear as 'canceled', since the team decided that we will not be working on this issue at the moment

**Comment by arboleya** [comment]
Could you please summarize the reasoning behind the decision?

**Comment by Dhaiwat10** [comment]
@anderson.arboleya sure:<br><br>The team decided that working on this issue will require a lot of work deep down the codebase of the abi-coder/typegen. It will probably require a significant amount of refactoring as well. The team decided that it is a better idea to not work on this right now so that we can focus on other priority issues, and to avoid any breaking changes at this moment
