### ISSUE TITLE
Method `assembleTransactionSummary` returns incorrect data

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-ts#1674]
### What version of fuels-ts are you using?

0.71.1

### Steps to Reproduce

Use `assembleTransactionSummary` and do not pass in the optional `gqlTransactionStatus` argument.

### Expected Behavior

`isStatusFailure`, `isStatusSuccess`, and i`sStatusPending` should return correctly based on the status of the transaction and its receipts

### Actual Behavior

`isStatusFailure`, `isStatusSuccess`, and `isStatusPending` always return `false` if gqlTransactionStatus is not passed in.

**Comment by arboleya** [comment]
Related:
 - https://github.com/FuelLabs/fuels-ts/issues/1578

**Comment by maschad** [comment]
Could you elaborate a bit more on the use case @matt-user ?  I'm curious because the [getTransactionSummary method](https://github.com/FuelLabs/fuels-ts/blob/0cda64a79fdba50783fd0267d9ba84b773f96d9b/packages/account/src/providers/transaction-summary/get-transaction-summary.ts#L25-L69) can be used to assemble a `TransactionSummary` can be used to see the transaction's status, indeed the  the [`processGraphqlStatus`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/transaction-summary/assemble-transaction-summary.ts#L79-L80) relies on the `gqlTransactionStatus` to return these values but that seems like expected behaviour.

**Comment by matt-user** [comment]
@maschad hmm yeah that makes sense.  It's been a while since I made this issue.  Let me look in our frontend code and get back to you.

**Comment by matt-user** [comment]
Yeah I think we can close this issue.  We ran into this because of a workaround which has now been fixed on the sdk side.
https://github.com/FuelLabs/fuels-wallet/issues/1236
