### ISSUE TITLE
Scripts are not working, getting error "The transaction reverted with an unknown reason: 123"

### ISSUE THREAD

**Issue by nadiia-balaian** [FuelLabs/fuels-ts#2284]
### What version of fuels-ts are you using?

82

### Steps to Reproduce

Create instance of the script and try to call its methods.

We created a script in rust sdk. Then I try to use them 
```

const scriptProxy = new Script(
    ScriptProxyAbiBytes,
    ScriptProxyAbi__factory.abi,
    options.wallet,
  );

const tx = await scriptProxy.functions
      .main(
        { WithdrawCollateral: withdrawCollateralInput },
        {
          value: new Address(BETA_CONTRACT_ADDRESSES.proxy.fuel).toB256(),
        },
        updateFee,
        priceFeedIds,
        updateData,
      )
      .callParams({ forward })
      .txParams({ gasPrice: 1 })

const { gasUsed: gasValue } = await tx.getTransactionCost();
const res = await tx.txParams({ gasLimit: gasValue }).call();
```

We tested script methods in rust sdk and there is no problems with that. 

When I try to call script methods inside ts sdk I got an error 
<img width="433" alt="Screenshot 2024-05-10 at 12 49 19" src="https://github.com/FuelLabs/fuels-ts/assets/109521832/1cc85209-9d35-4c6e-af0d-c4265a2cae12">

### Expected Behavior

Transaction is successfully  sent 

### Actual Behavior

Error "The transaction reverted with an unknown reason: 123"

**Comment by Torres-ssf** [comment]
@nadiia-balaian the revert reason `123` is defined within Sway [here](https://github.com/FuelLabs/sway/blob/76a6cd34a9b6c197926773afa53b7657cc08576d/sway-core/src/asm_generation/fuel/compiler_constants.rs#L40)

And it seems it is only being used [here](https://github.com/FuelLabs/sway/blob/master/sway-core/src/asm_generation/programs/abstract.rs#L269)

This error happens when a contract was called with a method unknown for that contract

**Comment by nadiia-balaian** [comment]
We found the root cause of the issue – it was an outdated Pyth contract and ABI on our side.
Thanks for your assistance with this
