### ISSUE TITLE
Issue with transaction execution error: Execution of the script associated with contract resulted in a non-zero exit code: 1.

### ISSUE THREAD

**Issue by nadiia-balaian** [FuelLabs/fuels-ts#2356]
### What version of fuels-ts are you using?

79

### Steps to Reproduce

Hello everyone,

We have a smart contract available [here](https://github.com/compolabs/swaylend-contracts). The tests for its functions using the Rust SDK have passed. However, when I try to call these functions with the TypeScript SDK, I encounter the following error: "Execution of the script associated with contract resulted in a non-zero exit code: 1."

To reproduce the issue, please follow these steps inside the swaylend-contracts directory:
```
forc build
cargo run --bin deploy
bash build.sh // ensure swaylend-contracts and spark-ts-sdk are in the same folder
```
After running these commands, you will obtain a new Market contract address.

On [this branch](https://github.com/compolabs/spark-ts-sdk/tree/feat/1017-lend-logic), there are tests for the Market contract. You need to replace the old contract address in [src/constants/index.ts](https://github.com/compolabs/spark-ts-sdk/blob/feat/1017-lend-logic/src/constants/index.ts#L37) with the new contract address.

Once you have updated the contract address, simply run `npm run test ./tests/lend-market.test.ts` to check the results.

Could you please help me identify what might be causing this issue?

Thank you!

<img width="989" alt="Screenshot 2024-05-20 at 16 26 53" src="https://github.com/FuelLabs/fuels-ts/assets/109521832/ea969773-6888-4457-aa5c-2b4c776f59c9">

### Expected Behavior

 Transactions complete successfully

### Actual Behavior

Transactions are failed

**Comment by maschad** [comment]
Hey @nadiia-balaian thanks for opening this issue, could you share which versions of the toolchain you are using? you can just run ```fuelup show``` and share the output of the console. I'm having issues compiling the contracts.

**Comment by nadiia-balaian** [comment]
hey @maschad 
<img width="488" alt="Screenshot 2024-05-21 at 09 49 57" src="https://github.com/FuelLabs/fuels-ts/assets/109521832/34bf6eb6-39ec-4e29-a7e5-1755eedb399e">

**Comment by Torres-ssf** [comment]
@nadiia-balaian Looking at the print image that shows the receipts array, I can see a `Revert` receipt with the hex value `0x7b` which is the decimal `123`. 

<img width="989" alt="Screenshot 2024-05-20 at 16 26 53" src="https://github.com/FuelLabs/fuels-ts/assets/109521832/ea969773-6888-4457-aa5c-2b4c776f59c9">

So it appears that you are having the same error as [before](https://github.com/FuelLabs/fuels-ts/issues/2284)

This error is shown differently from [here](https://github.com/FuelLabs/fuels-ts/issues/2284) because you are using `0.79.0`. 

On `0.82.0` we improved how error messages are shown.
