### ISSUE TITLE
chore: migrate away from `lerna` 

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#236]
https://github.com/lerna/lerna/issues/2703 :( 

We should get an alternative

**Comment by luizstacio** [comment]
I think would be possible to move to a simpler solution using `yarn|npm workspaces`?

**Comment by biantris** [comment]
Here are some of the most used tools for monorepo, I think turborepo is a good way https://monorepo.tools/#monorepo-tools
https://github.com/vercel/turborepo

**Comment by pedronauck** [comment]
I have been using [Turborepo](https://turborepo.org/) and [PNPM](https://pnpm.io/) for a few months and the experience with them is awesome, mainly because of the cache system that both have that speeds up package installations and build so much faster than others.

**Comment by pedronauck** [comment]
Hey guys, I started to play with this issue today trying to resolve some of these tasks:

- [x] Add Turborepo as monorepo manager
- [x] Change to PNPM instead of NPM
- [x] Use imports directly without the need to `build --watch` packages internally
- [x] Use [tsup](https://tsup.egoist.sh/) for build using `esm | cjs | iife` formats
- [x] Change Github actions to use PNPM
- [ ] Tests Github Actions
- [ ] Use [Auto](https://github.com/intuit/auto) or [Rush](https://rushjs.io/) for publishing instead of Lerna

👉🏻 And after some changes I struggle with other issues (that's already solved too):

- [x] Create an `index.ts` entry point for `wordlists` and `merkle-shared` packages in order to follow monorepo "pattern"
- [x] Use [set-project-references](https://github.com/Bessonov/set-project-references) for fix typescript references (the old package is not compatible with PNPM)

👌🏻 Until now things are doing very well, all tests are passing...

![Image](https://user-images.githubusercontent.com/2029172/166400340-06289af0-1791-44fe-be2b-2315d04793c0.png)

---

Now we have some new benefits because of the new toolchain:

✅ A very good cache system on the build pipeline (thanks to Turborepo)
✅ So much faster package installations (thanks to PNPM)
✅ Consume packages internally without watch builds
✅ Better `package.json` definitions with specific builds for CommonJS and ESM modules (thanks to tsup)

---

🙄 The only thing I'm lit stuck is `build` command on `example-project`. I don't know why, but it's with an error when trying to find the `typechain-target-fuels`, I'll try tomorrow to find why, but some help is very welcome.

```bash
> fuels-ts@0.0.1 build:example /Users/pedronauck/Projects/fuel/fuels-ts
> pnpm --filter '@fuel-ts/example-contract' build


> @fuel-ts/example-contract@0.6.0 build /Users/pedronauck/Projects/fuel/fuels-ts/packages/example-contract
> exec ./scripts/build.sh

Error occured:  Couldn't find fuels. Tried loading: @typechain/fuels, typechain-target-fuels, /Users/pedronauck/Projects/fuel/fuels-ts/packages/example-contract/fuels.
Perhaps you forgot to install @typechain/fuels?
Run with --show-stack-traces to see the full stacktrace
/Users/pedronauck/Projects/fuel/fuels-ts/packages/example-contract:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @fuel-ts/example-contract@0.6.0 build: `exec ./scripts/build.sh`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

---

Another thing is that now I have a big PR and maybe this can be an issue too. I'll try to split this into smaller ones!

**Comment by adlerjohn** [comment]
> I'll try to split this into smaller ones!

Please do ❤️! Big PRs are impossible to review properly.
