### ISSUE TITLE
chore: Update the logger to output the correct version

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#237]
We are currently using `ethers.js` logger and hardcoded the version to be 
```
const logger = new Logger('0.0.1');
```

We can either update the logger or make the version dynamic.

**Comment by camsjams** [comment]
@QuinnLee I will look into some options here, including the ones suggested

**Comment by camsjams** [comment]
We can use the compile-time environment variables feature of the newly added `tsup` bundler to set version string like:
```
 "scripts": {
    "build": "tsup --dts --env.BUILD_VERSION $BUILD_VERSION"
  }
```

Where `$BUILD_VERSION` would need to be created as part of CI process, which I also have working.  I did notice that the generated version string relates heavily to https://github.com/FuelLabs/fuels-ts/pull/242, so I would like to wait and see where that falls so that they all match.

Once compile-time environment variable exists, its easy to use and compiles this 
`const logger = new Logger(process.env.BUILD_VERSION');`

Into:
`E.Logger("0.0.0-master-47c3848")`
