### ISSUE TITLE
Handle `create fuels`  example dApp scenarios for insufficient funds 

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2463]
### Description

When a user submits a transaction with insufficient funds, they should be notified why the transaction hasn't been sent in an error modal with a link to redirect to the faucet

**Comment by Dhaiwat10** [comment]
@petertonysmith94 In my opinion, instead of redirecting the user to the faucet directly, we should instead include a link to the faucet in the error toast that we are currently showing. 

I am also aware that sometimes, we just throw an error which is not being catched which means no error toast is shown. This should indeed be taken care of

Thoughts?
