### ISSUE TITLE
Incorrect ESM types

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2482]
As part of #1776, we fixed the runtime issues that were being thrown for ESM based packages. However, the side note of incorrect types as specified by [`AreTheTypeWrong`](https://arethetypeswrong.github.io/?p=fuels%400.89.2).

- [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md)

<img width="292" alt="Screenshot 2024-12-03 at 14 49 11" src="https://github.com/user-attachments/assets/7a540eb6-6141-44a4-9077-d23c749bd1b9">

**Comment by danielbate** [comment]
Just done a new check on [arethetypeswrong](https://arethetypeswrong.github.io/?p=fuels%400.97.0) and we have resolved some problems, only the masqueraded ESM now so going to update the description.

**Comment by petertonysmith94** [comment]
There is a [CLI utility](https://www.npmjs.com/package/@arethetypeswrong/cli) for testing the packages locally.

I think the [following PR](https://github.com/FuelLabs/fuels-ts/pull/1889/files#r1553921740) might be helpful.


## Currently

From what I remember - the issue with our distribution is that we share the types between both ESM and CJS:

```console
└─ dist
    ├── index.d.ts
    ├── index.d.ts.map
    ├── index.js
    ├── index.js.map
    ├── index.mjs
    └── index.mjs.map
```

## Expected

So then the types aren't shared between them.

```console
└─ dist
    ├─ cjs
        ├─ index.d.ts
        ├─ index.d.ts.map
        ├─ index.cjs
        └─ index.cjs.map
    └─ mjs
        ├─ index.d.ts
        ├─ index.d.ts.map
        ├─ index.mjs
        └─ index.mjs.map
```

**Comment by danielbate** [comment]
Ty, I will check those out, I think I am reading something [similar](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md#common-causes).

**Comment by danielbate** [comment]
Okay so for this as @petertonysmith94 mentions we need to separate our distribution files between CJS and ESM. The expected way for this though is to create a `*.d.mts` file for ESM typings. Using a single dist seems to be a common problem for projects shipping using `tsup`. There's a couple open issues right now for `tsup` to provide more config around dist files for ESM.

I think we keep an eye on these issues ([1](https://github.com/egoist/tsup/issues/939), [2](https://github.com/egoist/tsup/pull/1235)) to see how things develop and me may be able to fix this through `tsup`. But shipping both CJS and ESM from a single package seems like a very prevalent issue in the TS lib world.

I'm going to close this for now as we haven't had any reports since #1776 and our `AreTheTypeWrong` report has improved since then. We only have the masqueraded types issue, which seems more nuanced and up for discussion.
