### ISSUE TITLE
Add `Getting started` tutorial to docs with a simple example Dapp 

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#259]
### How to create a Dapp
- How to start a project
- What to install `fuels` etc

Ref.: https://github.com/FuelLabs/swayswap

**Comment by luizstacio** [comment]
@camsjams I think would be nice to add a link for this demo on the `fuels-ts docs` also

**Comment by AlicanC** [comment]
Would be cool if we had some CodeSandbox links like: https://codesandbox.io/s/currying-flower-gjpiik?file=/src/App.tsx

People could click a link and start hacking on the example right away. I can't think of any easier way to experience Fuel as a developer TBH. I'd say `fuels-ts` has the power and responsibility to be the fastest and easiest way to hack on Fuel. We can really shine here!

See: https://codesandbox.io/docs/importing#import-from-github
See: https://codesandbox.io/docs/configuration

**Comment by AlicanC** [comment]
The Provider can point to the official testnet deployment. (Not sure what the URL for that is ATM. Infra should know.)

For the wallet, we could just generate a random one and store it in LocalStorage. I don't know how we would do fauceting though. We could maybe copy the fauceting code from SwaySwap. One thing I don't like about that is we would need to add Google reCAPTCHA to these projects. Maybe that's okay since we won't need it when we have a web wallet.

**Comment by luizstacio** [comment]
We are looking for a codes andbox to only play with `fuels-ts SDK` or also `Contracts`?
