### ISSUE TITLE
Upgrade `@types/node` from 16.18.34 to 20.14.10

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2667]
### Summary

The following dependabot PR was closed:
- #2661

On upgrade to the `@types/node` the following build [failure](https://github.com/FuelLabs/fuels-ts/actions/runs/9738906680/job/26873201409?pr=2661#step:3:817) was occuring:

```console
Error: src/providers/provider.ts(399,44): error TS2339: Property 'timeout' does not exist on type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```

This was caused by the following line of code:
https://github.com/FuelLabs/fuels-ts/blob/36082df0a6cc337a9de8b2f297e14a45baec1c78/packages/account/src/providers/provider.ts#L399

### What we need to do

- Reinstate the upgrade from #2661
- Investigate and fix issue with the timeout property

**Comment by mvares** [comment]
I've been investigating this issue and it seems that the problem is related to the Node version. I found other issues that describe the same problem.

Perhaps we will need another approach if we want to maintain `AbortController.timeout()`. The solution that the maintainers of other projects found was to use version `20.0` or higher.

**Comment by mvares** [comment]
Well, yes. But our code supports the version 18.0.
