### ISSUE TITLE
Improve BigInts UX

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#280]
We moved from Ethers v5 BigNumbers to native JS BigInts in #258.

While the UX has been generally fine, the native `JSON.stringify` does not support BigInts so the users might get `Do not know how to serialize a BigInt` errors, both from their own usage of it (which they could fix) and also from the libraries they use (which they might not be able to).

One example issue is this, where Jest fails to render the actual error if the error involves a BigInt: https://github.com/facebook/jest/issues/11617#issuecomment-1028651059

(The solution is starting Jest with `--maxWorkers 1` which probably disables the thing that can't handle BigInts.)

We should further investigate the UX of native BigInts. If we find them unworthy then we can stop using them in output positions so users never get BigInts while we can keep using them.

(Or maybe we could make the build system polyfill BigInts.)

**Comment by luizstacio** [comment]
On SwaySwap `bigints` prove to be really hard to handle convert parse, etc. And it didn't remove the requirement of having some utilities and also some other big number libs to work: #165 and also https://github.com/FuelLabs/swayswap/blob/master/packages/app/src/systems/Core/utils/math.ts

**Comment by LuizAsFight** [comment]
nice catch @AlicanC I didn't know it.

as mentioned in [Serialize JSON](https://tc39.es/proposal-bigint/#sec-serializejsonproperty) - step 10.
Ref: [GoogleChromeLabs/jsbi/issues/30]



as `number` type has this max size limitation: `Number.MAX_SAFE_INTEGER` = `9007199254740991`, we cannot use it safely.

[bigint](https://github.com/tc39/proposal-bigint) was created to address it natively, but still have its problems. I think we should never expose something that can break in a command often used like `JSON.stringify` (state libraries, save data to local storage, parse data to send to back end, and other use cases). And for internal use, it's not totally supported as some projects may compile for `es5` for example, and would need to upgrade to `es2020` minimum, which the user might not want.

Instead of going with native `number` or `bigint`, I think would be good to use some big number library, plenty of options in npm.

[BN.js](https://www.npmjs.com/package/bn.js) is a good one:
- they're used by [elliptic](https://www.npmjs.com/package/elliptic) curve project.
- BN.js is
> Optimized for elliptic curves that work with 256-bit numbers. There is no limitation on the size of the numbers.

It supports sizes that we need and it's pretty complete with a lot of helpers.

I think we should create a lib that uses BN.js in the background and have some additional helpers that we will need, like some presents in **SwaySwap** [swayswap/math.js]( https://github.com/FuelLabs/swayswap/blob/master/packages/app/src/systems/Core/utils/math.ts).
The user should not need to write all these helpers and deal with `ethers` in the front end project, 
- parse to units functions (instead of user needing to deal with  in the project)
- basic math helpers (divide always valid ... so on)

When stringifyed it exposes a hex which will work as JSON common string and not break anything
![image](https://user-images.githubusercontent.com/8636507/179877220-4726fcb8-1bed-43db-adb5-ecd4b9b44a74.png)
