### ISSUE TITLE
Connector may arbitrary change on component re-render if several wallets are installed

### ISSUE THREAD

**Issue by svvald** [FuelLabs/fuels-ts#2892]
### fuels-ts SDK Version

0.92.1

### Toolchain Versions

forc: 0.62.0, fuel-core: 0.31.0, fuel-core-keygen: 0.31.0

### Node.js Version

v20.15.1

### Browser

Google Chrome 127.0.6533.89 (Official Build) (x86_64)

### Operating System

macOS Sonoma 14.5 (23F79)

### Describe the Problem

Pre-requisites:
React web application – `react v18.3.1`, `next v14.2.5`, `@fuels/react v0.20.0`
Wallets installed – `Fuel v0.23.0`, `Fuelet v1.0.29`

Steps to reproduce:
– Establish connection with Fuelet wallet
– Re-open/refresh the page
– Interact with some component which uses several hooks from `@fuels/react`, specifically `useIsConnected`. Interaction leads to component re-render upon which connection status from the hook may change to false

While investigating I discovered that on component re-render the active connector may arbitrary change to Fuel connector thus reporting the disconnected status. On debugging I discovered the following:
– `fuel` object seems to be re-instantiated on component re-render (it is used by `@fuels/react` internally via `useFuel` hook and, apparently, has to be memoized, I'm not sure why it doesn't happen, I do not re-render the whole application tree, so the context provider value doesn't have to be changed)

– While re-instantiating `fuel`, the following methods are invoked in its constructor:
```
this.setDefaultConnector();
this._targetUnsubscribe = this.setupConnectorListener();
```
Where the first one tries to setup the default provider via storage value if it's present (it is in my case, it is Fuelet wallet) or via config otherwise. And the second one setups listeners for connectors to be added to `fuel` object once they're initialized.
`addConnector` method on its turn tries to connect to the added connector, if no current connector is present:
```
if (!this._currentConnector) {
  await this.selectConnector(connector.name, {
    emitEvents: false,
  });
}
```
So the problem here is that `setDefaultConnector` is async, but its promise is ignored in constructor, so both methods are called synchronously, which may lead to the case when previously used connector is not yet obtained from the browser storage, but listeners for connectors are already set up, their events are invoked with Fuel being the first in the order and it ends up being set up as an active connector which results in connection loss for Fuelet wallet.

Hope it helps, I think I could come up with some fix for the second one if it sounds reasonable, from my perspective these two methods have to be chained so `fuel` will always try to set up default provider first. Although I suppose re-instantiating the `fuel` object is also not something that I would consider expected

**Comment by maschad** [comment]
Hi @svvald thanks for raising this issue. This is a good find, I've been able to reproduce this using https://connectors.fuel.network/ with Fuelet and Fuel Wallet (along with trying with Metamask and other Ethereum wallets) after several tries (I'd estimate once in every 50 tries or so). Neverthless, this is a valid bug, but I'd like to know if you have a means of reproducing this consistently for verification.

Looking at the fix you have proposed I believe it's valid, considering more than likely it's a race condition happening here due to the async nature of the control flow as you described. If you'd like to open a pull request with that PR feel free but I don't have a way of verifying that it solves the issue for all cases at the moment. Hence I'd like to know if you have your own reproducible example. If not, that's fine as well as I'd still welcome the fix you proposed.

**Comment by mpoplavkov** [comment]
Hi @maschad. We had an issue with that on https://mira.ly/, the bug would definitely reproduce after several tries. Right now, we added a crutch that modifies this behavior, so that it doesn't reproduce that often (but we have other problems with the crutch).

I guess, we can remove the crutch locally and test a new version of the connectors, once it's out, and return you some feedback if that works for you.

PS: we're waiting for this bug to be solved ASAP :)

**Comment by maschad** [comment]
Thanks for the clarification @mpoplavkov appreciate the info 😄 

I've [released](https://github.com/FuelLabs/fuels-ts/pull/2930#issuecomment-2287154187) a [patch fix](https://www.npmjs.com/package/fuels/v/0.0.0-pr-2930-20240813211727) you can run npm install as usual 

```
npm install fuels@pr-2930
```

Let me know if that resolves the issue, although I know it would be difficult to reproduce.

**Comment by svvald** [comment]
Hi @maschad, thank you for addressing this real quick!

I pulled your fix and tried to reproduce the issue, unfortunately I can't say it helped as it now leads to another problem – `fuel` not being able to provide any connectors at all.

By looking at code, I'm not sure invoking `ensureInitialized` is needed in each case you've used it. Also it doesn't resolve race condition of wallets listeners setup which is a cornerstone of this issue from my perspective.
I've created a [PR](https://github.com/FuelLabs/fuels-ts/pull/2940) which introduces the changes which might probably resolve our issue. I'd appreciate if you could approve publishing this PR to npm for me to test whether it works. Also I'd be glad to hear your thoughts on it as well as now it's just some sketchy solution which will need some proper implementation :)

**Comment by maschad** [comment]
Thanks for sharing your feedback @svvald 

> I pulled your fix and tried to reproduce the issue, unfortunately I can't say it helped as it now leads to another problem – fuel not being able to provide any connectors at all.
 
That's strange it would have that effect, I've tested out the fix on https://connectors.fuel.network/ using fuel-wallet, and it works fine for me. Would you be able to share the repo where you are experiencing the issue so that I could try to reproduce it?

> I'd appreciate if you could approve publishing this PR to npm for me to check on out test environment whether it works. 

I see that @petertonysmith94 has [created a test build](https://github.com/FuelLabs/fuels-ts/pull/2943#issuecomment-2291413015) so feel free to share your feedback here.

>  Also I'd be glad to hear your thoughts on it as well as now it's just some sketchy solution which will need some proper implementation :)

I'd like to look through the repro that's actually causing the issue so that I can make a more holistic assessment.

**Comment by mpoplavkov** [comment]
@maschad the repo is not open-sourced, but it seems that the [test build](https://github.com/FuelLabs/fuels-ts/pull/2943#issuecomment-2291413015) solved the issue for us

**Comment by maschad** [comment]
> @maschad the repo is not open-sourced, but it seems that the [test build](https://github.com/FuelLabs/fuels-ts/pull/2943#issuecomment-2291413015) solved the issue for us

I'm glad to hear that and thanks for sharing that feedback 😄 

I'm not sure if that will solve all potential race conditions though as the [IIFE that`initialize`](https://github.com/FuelLabs/fuels-ts/pull/2930/files#diff-f2f37286dc75888286dbb2da3164a73b4a4a1ea8a90d87fd1ec9bcee1666097cR106-R110) is wrapped in is still executed asynchronously, and so there's still a risk that methods called immediately after object creation might execute before the initialization is complete. There's also that risk with the test build I proposed as well (I had added the method guards to try reduce the possibility but it can still occur). 

> Also I'd be glad to hear your thoughts on it as well as now it's just some sketchy solution which will need some proper implementation :)

To avoid introducing breaking the constructor for now I've added a new [`init`](https://github.com/FuelLabs/fuels-ts/pull/2930/files#diff-f2f37286dc75888286dbb2da3164a73b4a4a1ea8a90d87fd1ec9bcee1666097cR117-R119) method which will allow a consumer to _await_ all initialization before continuing. 

```ts
const fuel = await new Fuel(config).init();
await fuel.someMethod();
```
