### ISSUE TITLE
Transaction Summary showing incorrect operations for faucet transaction

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2939]
### fuels-ts SDK Version

0.93.0 (next)

### Describe the Problem
The operations being shown for a faucet transaction are like following:
<img width="348" alt="image" src="https://github.com/user-attachments/assets/53185345-0bb4-48af-bf74-616c5ecca8b0">

### What's wrong
- The first operation is a transfer from the user account to the user account
- The second operation is a transfer from the user account to the faucet account

### How it should be
- One transfer operation from the faucet account to the user account with the faucet amount ( 0.002 ETH )
- One transfer operation from the faucet account to the faucet account ( remaining ETH amount from faucet account )

**Comment by Torres-ssf** [comment]
@LuizAsFight, I do not completely understand the problem here.

> How it should be
> - One transfer operation from the faucet account to the user account with the faucet amount ( 0.002 ETH )

This one is clear. The first shown operation cleared is wrong.

> One transfer operation from the faucet account to the faucet account ( remaining ETH amount from faucet account )

Why does the second operation needs to show a transfer operation from and to the faucet account with the remaining ETH amount owned by the faucet itself? 

Seems to me that this operation shouldn't exist in the first place.

**Comment by LuizAsFight** [comment]
you're correct it shouldn't exist, but if you look at the faucet transactions, instead of putting the "ChangeOutput" as the faucet account, it does another transfer to the faucet account

**Comment by Torres-ssf** [comment]
@LuizAsFight You’re right. The Faucet transfer indeed produces an unconventional use of outputs.

```ts
// Faucet Transfer TX outputs 
[
  {
    type: 0, // CoinOut to my address -> Everything is fine 👍
    to: '0xc2714e9248bc19510c412df5c6a6242abe36be85856e8be419baa78334ac7070', // My address
    amount: <BN: 0x1e8480>, // Normal value transferred by the faucet
    assetId: '0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07'
  },
  {
    type: 2, // ChangeOutput to my address -> This was supposed to be the faucet address 👎
    to: '0xc2714e9248bc19510c412df5c6a6242abe36be85856e8be419baa78334ac7070', // My address
    amount: <BN: 0xc088a>, // It uses only a small amount.
    assetId: '0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07'
  },
  {
    type: 0, // CoinOutput to faucet address? -> The faucet transferring for the faucet 👎 
    to: '0x8fea1e048029ee0ef395916298c345e0b6129cf33d2df940a782e78e6a403381', // Faucet address
    amount: <BN: 0x38d7e70360f58>, // The whole change amount of the faucet spent coin
    assetId: '0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07'
  }
]
```

This unconventional use of Transaction outputs resulted in the `getOperations` helper working unexpectedly.

I’m unsure why the outputs were assembled this way. They’re likely doing this hack for some reason.

Nevertheless, we can make the validation more robust, since this misuse of `OutputCoin` and `OutputChange` is outside our control.

**Comment by LuizAsFight** [comment]
using the`changeOutput` to define the sender is wrong, we should use the account that is funding the transaction (inputs)
