### ISSUE TITLE
Update Wallet to use ENV file for Provider URL

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#300]
Per #203 there is a todo within [@fuel-ts/wallet](https://github.com/FuelLabs/fuels-ts/blob/master/packages/wallet/src/wallet.ts#L21) to remove hardcoded `FUEL_NETWORK_URL` value of `'http://127.0.0.1:4000/graphql'`

**Comment by danielbate** [comment]
Would be happy to pick this up over the weekend if it's still available? There seems to be lots of hardcoded usage of `'http://127.0.0.1:4000/graphql'` throughout.

**Comment by arboleya** [comment]
@danielbate If you ignore the occurrences inside test files _(it seems to me like those should remain as is)_, only one is left:

https://github.com/FuelLabs/fuels-ts/blob/2d70903c980a738bee82bdd1181ed84545b6aa66/packages/wallet/src/constants.ts#L2

It is used as a default param assignment in some methods, like this:

https://github.com/FuelLabs/fuels-ts/blob/7d3416d5631c124bf7d89e5451bc206f0d93dc2a/packages/wallet/src/base-locked-wallet.ts#L42

So, deleting the `FUEL_NETWORK_URL` constant would require changing all relevant method signatures using it _(i.e., removing the default param assignment)_ and updating all broken usages of such methods.

@FuelLabs/sdk-ts Makes sense?

**Comment by danielbate** [comment]
@arboleya makes sense and thank you for the explanation, I can address that later.

Outside the scope of this issue, would be happy to raise another if you agree, but I do think there is a case for all urls to be config/env driven, even in tests. I run a couple local tools, one of which already running on port 4000. I opted to change the port that the `fuel-ts` container was running on rather than bringing down my own containers. Then had to do a find and replace to run the test suite when making changes. 

So the constant for `FUEL_NETWORK_URL` could be something like export const `FUEL_NETWORK_URL = process.env.FUEL_NETWORK_URL || 'http://127.0.0.1:4000/graphql';`. Or use a package like @node-config/node-config to dictate the value, and drive it from a config file.

**Comment by LuizAsFight** [comment]
makes sense @arboleya , maybe we could create a env var to hold `http://127.0.0.1:4000/graphql` instead ? then could do something like....

`export const FUEL_NETWORK_URL = process.env.FUEL_PROVIDER_URL`
