### ISSUE TITLE
Investigate Why Test Files Are Being Ignored By Lint Script

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#3027]
We need to investigate why test files are being ignored by the [lint](https://github.com/FuelLabs/fuels-ts/blob/e14f7d4c363a60db05aadbbd38890822cac99367/package.json#L34C6-L34C10) script

More context [here](https://github.com/FuelLabs/fuels-ts/pull/3026#pullrequestreview-2257985068)

**Comment by maschad** [comment]
Looking at the issues in the [linked PR](https://github.com/FuelLabs/fuels-ts/pull/3026) they look like typing issues. My suspicion is that currently we don't build a lot of the test files due to our [`tsup.config.ts`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/abi-coder/tsup.config.ts#L1) files configurations

**Comment by arboleya** [comment]
Maybe we could make the [`scripts/postbuild.ts`](https://github.com/FuelLabs/fuels-ts/blob/master/scripts/postbuild.ts) script run an additional `tsc` step only in CI to catch these things.
