### ISSUE TITLE
Spending a Predicate should not require a Wallet, just a provider

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#392]
### Motivation

After reviewing specs and implementation, its clear that spending the locked coins in an existing Predicate should not require using a Wallet, just the Provider.

### Usage example

Update this [function](https://github.com/FuelLabs/fuels-ts/blob/master/packages/predicate/src/predicate.ts#L140) to use a `Provider` instance instead of a `Wallet`.

### Possible implementations

Update the spend predicate function and tests to use the Provider directly. 

For the tests, can probably just change it like this:
```diff
    const initialPredicateBalance = await setupPredicate(wallet, amountToPredicate, predicate);
    const initialReceiverBalance = await wallet.provider.getBalance(receiverAddress, NativeAssetId);

-    await predicate.submitSpendPredicate(wallet, initialPredicateBalance, receiverAddress);
+    await predicate.submitSpendPredicate(wallet.provider, initialPredicateBalance, receiverAddress);
```

And then update implementation of `submitSpendPredicate` to use this parameter type.

The spending step of a Predicate requires:
- provider
- amount of coin
- asset id
- receiver address

and optionally:
- predicate data

**Comment by luizstacio** [comment]
@camsjams, I think the predicate should be treated as a new Signer Module... enabling the Wallet to be instantiated with a predicate. Does it make sense?

Or it could be a Wallet Vault on the Wallet Manager.

**Comment by luizstacio** [comment]
> > I think the predicate should be treated as a new Signer Module... enabling the Wallet to be instantiated with a predicate. Does it make sense?
> > Or it could be a Wallet Vault on the Wallet Manager.
> 
> @luizstacio Can you drop a link or example?

I don't have a very good example because it would be something new.
But, the idea is to make predicate work for SDK users like a Wallet and also integrate with all parts that already use Wallet.

The main changes would be;
- Abstract common methods like `transfer`, `fund`, `sendTransaction` to a BaseWallet class.
- Remove/Implement a signer class [here](https://github.com/FuelLabs/fuels-ts/blob/7c556e696fd99fb90ccb4d2d6c3bba535b0df562/packages/wallet/src/wallet.ts#L37).
- Update the `populateTransactionWitnessesSignature` to populate the predicate data on the transaction.
