### ISSUE TITLE
Implement generic on typechain

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#430]
### Motivation

After `0.18.1`, sway is supporting `typeArguments` in ABI.

But `type` field inside `components` doesn't tell what type is being set (as mentioned in [sway/2386](https://github.com/FuelLabs/sway/issues/2386)). Then we don't know what dynamic type is being set for each argument. Instead we just have the final type.

After this issue is merged [sway/2386](https://github.com/FuelLabs/sway/issues/2386), we should implement dynamic typing in typechain

This is also blocked by the implementation on the ABI: #431

**Comment by luizstacio** [comment]
With the new flat ABI, it's not possible to use the default implementation of the [typechain](https://www.npmjs.com/package/typechain); the issue is related to the way the typechain checks if an abi file is empty or not ([see file line in typechain](https://github.com/dethcrypto/TypeChain/blob/92faf28a91fa17a6cb9c34bd29ea9b2cae5d57b3/packages/typechain/src/typechain/io.ts#L42)). 

I have implemented locally a solution for typechain to support a external `extractAbi` function witch is provided on the typechain target. I'm going to open a PR on typechain.

**Comment by luizstacio** [comment]
> With the new flat ABI, it's not possible to use the default implementation of the [typechain](https://www.npmjs.com/package/typechain); When using it, the typechain throws `Error occured: Not a valid ABI`. This issue is related to the way the typechain checks if an abi file is empty or not ([see file line in typechain](https://github.com/dethcrypto/TypeChain/blob/92faf28a91fa17a6cb9c34bd29ea9b2cae5d57b3/packages/typechain/src/typechain/io.ts#L42)).
> 
> I have implemented locally a solution for typechain to support a external `extractAbi` function witch is provided on the typechain target and added the implementation for the flat ABI JSON on the `typechain-target-fuels`. I'm going to open a PR on typechain to see if is possible to get this new feature.

https://github.com/dethcrypto/TypeChain/pull/757
