### ISSUE TITLE
docs: current quickstart is not compatible with fuel-core +0.10

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#459]
## This issue is open as a source of information

The current quickstart uses the `fuelup` to install the toolchain, which currently installs fuel-core `v0.10`, which is not compatible with the current TypeScript SDK. 

The temporary solution is to install from source code or using `fuel-core` version `v0.9.6`.
```sh
cargo install fuel-core --version=0.9.6 --force
```
Or use the docker image.
```
docker run \
    --platform=linux/amd64 \
    -v <complete path>/chainConfig.json:/chainConfig.json \
    ghcr.io/fuellabs/fuel-core:v0.9.6 \
    ./fuel-core run \
    --ip 127.0.0.1 \
    --port 4000 \
    --chain /chainConfig.json
```

This will be fixed with:
- [ ] https://github.com/FuelLabs/fuels-ts/issues/453

**Comment by bingcicle** [comment]
To expand on the details surrounding the upcoming fuelup release:

Once `fuelup v0.3.0` is released, `fuelup` will use [channels](https://fuellabs.github.io/fuelup/master/concepts/channels/index.html) as the source of truth when installing official toolchains such as `latest`. In this case the channel [here](https://github.com/FuelLabs/fuelup/blob/2a03e79e292e45b88cbd983a1565c85c72e227bf/channel-fuel-latest.toml) would be used as the source of truth - `fuel-core v0.10` is not used here since `fuelup` runs tests of newly released `forc` and `fuel-core` and determined them to be incompatible with each other. 

[Custom toolchains](https://fuellabs.github.io/fuelup/master/concepts/toolchains.html#custom-toolchains) are more expressive in that you can directly specify the version of a component to install and use in a toolchain, and you will be able to switch between the official toolchain and a custom toolchain using `fuelup default`.
