### ISSUE TITLE
Remove static binary from `contract/multicall`

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#467]
Currently, we build contract calls using a sway script with the main function that expects params. The support for it was removed on sway +0.20. which creates a breaking change for fuels-ts.

When support for it is implemented, we can remove the `static-out`. 

Blocked by:
 - ~https://github.com/FuelLabs/sway/issues/845~
 - https://github.com/FuelLabs/sway/issues/3086

**Comment by arboleya** [comment]
@luizstacio I'm afraid I didn't get what exactly I should do here.

Could you please elaborate on it a bit further?

**Comment by luizstacio** [comment]
This folder https://github.com/FuelLabs/fuels-ts/tree/master/packages/contract/src/contracts/multicall/static-out has a locally compiled built contract that was committed with the code, because we had some issues in the past between the current forc version and the features we required.

Now with the latest forc it should not be needed, and we should;
1. Delete the static-out
2.[ Change the import link](https://github.com/FuelLabs/fuels-ts/blob/1eb02569008292621cd69647bc78044df6ec3103/packages/contract/src/scripts.ts#L12) to the output bytecode from the folder that is generated build time. [./packages/contracts/scripts/build-multicall](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/scripts/build-multicall.sh).

**Comment by arboleya** [comment]
> **NOTE**: The [build-multicall.sh](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/scripts/build-multicall.sh) is **_not_** called at build time.

Attempts:
 1. When I run the [build-multicall.sh](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/scripts/build-multicall.sh) manually, I get an error due to this [_hardcoded path_](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/src/contracts/multicall/Forc.toml#L6) on `Forc.toml`.
 2. If I clone the [`sway`](https://github.com/FuelLabs/sway) repo and update the hardcoded path to use it, I get another error:
```shell
error
   --> fuels-ts/packages/contract/src/contracts/multicall/src/main.sw:100:9
    |
 98 |
 99 |     asm(ptr: buf.ptr(), len: buf.len()) {
100 |         retd ptr len;
    |         ^^^^ Unrecognized op code.
101 |     }
```

Questions:

 1. What version of `sway` should be used to compile these contracts?
 2. How could we get rid of the _hardcoded_ local path to `sway/sway-lib-std` inside `Forc.toml`?
    > _Using a local hardcoded version seems prone to future problems_
 4. Should the script `process-multicall` be executed automatically at build time?
    > _If so, it is one more reason not to have _hardcoded_ stuff, or the CI will crash_
