### ISSUE TITLE
Accept address as `String` instead of `Address`

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#748]
When using;
- `BaseWalletLocked.<transfer|buildPredicateTransaction
|submitPredicate>`
- `Provider.<getCoins|getResourcesToSpend|getBalance|getBalances|getMessages|buildSpendPredicate|submitSpendPredicate>`
- `BaseTransactionRequest.<updateWitnessByOwner>`

These methods require the Application to instantiate an Address object before executing the methods, as bech32 and hex are both strings and can be differentiated by string evaluation. All the methods should be able also to receive a string. Making address param type from `AbstractAddress` to something like`string | AbstractAddress`. And use `Address.fromDynamicInput` internally for the correctness of the data.

> [!NOTE]
> - Related to https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by arboleya** [comment]
I would advocate accepting only `string` instead of `string | AbstractAddress`.

Still on the same wave about _[avoiding parameter type overloading](https://github.com/FuelLabs/fuels-ts/pull/746#pullrequestreview-1264101092)_ and why it [_sounds_](https://github.com/FuelLabs/fuels-ts/pull/746#discussion_r1083677506) like the thing [_to do_](https://github.com/FuelLabs/fuels-ts/pull/746#discussion_r1084296559).

For this issue, this means that:
 1. It is a breaking change
 1. It requires refactoring all places currently using the affected methods
     - _Mostly purging boilerplate-code anyways_
 1. It sucks

Still, I think it is worth it.

Thoughts?

> cc @FuelLabs/sdk-ts

**Comment by luizstacio** [comment]
I think is good to accept both once the code you implement the call can have an Address instance and forcing it to transform into a string to then pass the param, would not be so good as just accepting both.

**Comment by Dhaiwat10** [comment]
@arboleya I would lean towards simplicity, too.

Our methods only accepting `string` inputs and our code _internally_ taking care of all the complexity around parsing the input & processing it further sounds like a better experience for our users than the methods accepting inputs of multiple shapes and our internal code _still_ having to do some processing depending on the shape of the input _anyways_. 

The former approach sounds like it makes things super simple for the users, while the latter sounds like it involves a compromise on both ends.

**Comment by LuizAsFight** [comment]
I agree inputs should be more flexible.. `string | AbstractAddress` sounds good to me


but I remember we kept `Address.from....` approach in name of security, but now using `Address.fromDynamicInput` in a lot of places with only a string input doesn't skip that security thought? sounds weird to me... not related to this issue but I still think `new Address(string)` should just do the job instead of having `from......`

**Comment by arboleya** [comment]
@LuizAsFight It looks like you have a valid point with the `fromDynamicInput` thing.

----

@luizstacio By having the address `string` representation saved and always accessible, the idea is that we wouldn't need to convert anything or pass class instances back and forth.

```ts
class SampleClass {
  address: string; // always accessible
  constructor(address: string) {
    this.address = address;
    this.abstractAddress = Address.fromDynamicInput(this.address);
  }
}

class OtherClass {
  constructor(address: string) {
    // ...
  }
}

const abc = new SampleClass('0x...');
const xyz = new OtherClass(abc.address); // `abc.address` instead of `abc`
```

----

@Dhaiwat10 Precisely, thanks for putting it so eloquently. Reducing the number of questions one will ask when reading the code seems favorable, and that's the opposite of what types-overloading causes, IMO.

I suspect that upon seeing `address: string`, the likely reaction would be:
 - _Paste the address_

Whereas `string | AbstractAddress` _could_ raise other questions, i.e.:
 - _What is `AbstractAddress`_?
 - _Why and when should I use it_?

Seeing one thing in isolation might not transmit the complexity that simple decisions can add _(or remove)_, but it can quickly become noticeable when the same habit is repeated throughout the codebase.

**Comment by arboleya** [comment]
@camsjams All address formats are represented as a `string` type, and no amount of boilerplate code or manual instantiation will remedy the fact that we have multiple formats by design. 

Our code strictness will not change regardless; the detection/validation logic is already in place and can never be removed. Nothing will change internally. We'd be adding an obstacle, not a feature.

It also adds no security. No matter what or how many steps we add, the underlying format will forever be a `string`. Shifting the remote possibility of mistakes to the left or right, adding one or several steps in between, makes no difference.

The point @LuizAsFight brought up about `Address.fromDynamicInput` only proves that not even we can't stand this approach, falling back to an umbrella method everywhere to get around it.

No matter the angle I look at it, I continue adamantly about simplicity being the ultimate aim.

**Comment by luizstacio** [comment]
The idea is that we should accept strings but check for a format bech32, this will keep the security but make it simpler for developers. The utilities around the Address will be provide if the user don't have the correct address it would be possible to convert.

But asking for an Address object makes things more difficult and not add security as already mention, when using it, we always do Address.from<...> and pass it along.

**Comment by arboleya** [comment]
@camsjams Thanks for the thorough explanation and link to the original PR.

Could you please exemplify these three cases _(`current style`, `string style`, `optimized string style`)_ with simple code snippets from a user's perspective when consuming the SDK? That can be clarifying.

I will also try simulating these cases while reviewing the source code again to understand it better.

**Comment by arboleya** [comment]
@LuizAsFight Do you remember the places where you mentioned that `Address.fromDynamicInput` is used? This can also help contextualize this conversation since we're going back and forth between ideals and real-world case scenarios.

**Comment by LuizAsFight** [comment]
feels bikeshedding such a long discussion because of 1 type more in input... this problem only happens because we don't have a standard way of using this inputs for Address

What I would do: same pattern of `math/bn`

- create AddressInput
```
  type AddressInput = Bech32Address | B256Address | string | AbstractAddress;
// could even include `BytesLike` here? I see it's used in `isBech32` function
```
then Address constructor is the place that validate everything and guarantee a valid/safe Address. for example
```
  constructor(address: AddressInput) {
    super();
    logger.checkNew(new.target, Address);
    if (typeof address === 'string') {
      if (isB256(address)) {
        this.bech32Address = toBech32(address);
      }

      if (isBech32(address)) {
        this.bech32Address = normalizeBech32(address as Bech32Address);
      }

      if (isPublicKey(address)) {
        this.bech32Address = toBech32(sha256(address));
      }
    } else {
      this.bech32Address = address.toAddress();
    }
    
    if (!this.bech32Address || !isBech32(this.bech32Address)) {
      logger.throwArgumentError('Invalid Address', 'address', address);
    }
  }
```


-----------------
### On this way you don't have problems or decisions to do regarding inputs

anywhere you need address input you will use:
```
export function test(address?: AddressInput) {
  const created = new Address(address);

  // from here on you know your `created` variable is a valid address.
}
```

or if you don't wanna allow flexible inputs, but only string... would work on exact same way:
```
export function test(address?: string) {
  const created = new Address(address);

  // from here on you know your `created` variable is a valid address.
}
```

### plus

Using different `from...` to create an Address introduces split rules, opening room for problems. for example RN only looking to `fromString` code
```
  static fromString(address: string): Address {
    return isBech32(address) ? new Address(address as Bech32Address) : this.fromB256(address);
  }
```
it can be broken because it suppose when it's not a Bech32, it's a b256 ?? I didn't test but looks like.

but this will only happen if you use `fromString`... if you use `fromDynamicInput` then there're other rules.
if we do like I mentioned before, you centralize responsibility for a valid Address. I don't like the idea of having static functions with part of the responsibility to have a valid address output.

**Comment by LuizAsFight** [comment]
> @LuizAsFight Do you remember the places where you mentioned that `Address.fromDynamicInput` is used? This can also help contextualize this conversation since we're going back and forth between ideals and real-world case scenarios.

@arboleya it's a new thing I guess it's not used everywhere, sorry if I meant it. My comment was just pointing it out because this issue mention using Address.fromDynamicInput

**Comment by luizstacio** [comment]
I open a draft PR for better understand the issue, and open it for discussion https://github.com/FuelLabs/fuels-ts/pull/801

**Comment by arboleya** [comment]
Completed via #1583.
