### ISSUE TITLE
Move from Jest to a more suitable alternative

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#813]
Although Jest does the job and has done it so far _(although slower than I'd like)_ we should consider seeking a better alternative, possibly more modern and performant. Speed is paramount in tests, and Jest seems to fall short.

Vitest seems a strong candidate:
 - https://vitest.dev/guide/migration.html#migrating-from-jest

**Comment by Dhaiwat10** [comment]
@arboleya I agree. I will add something:

I feel like we should re-evaluate #728 since it has been blocked/stuck for a long time, and maybe just rename the issue to _'Switch to a new testing setup'_ and include switching to a new test runner in that issue. All of this feels like a part of one big problem that we are trying to solve.

We can first switch to a new test runner, and then look into how we can run those tests in a browser. Putting in more work into figuring out how to run the tests in a browser with Jest, only to switch to a different test runner soon doesn't sound ideal.

**Comment by Dhaiwat10** [comment]
@camsjams I went through that thread that you linked, someone suggested having a look at [karma-vite](https://github.com/credred/karma-vite)

**Comment by Dhaiwat10** [comment]
This comment also seems interesting, seems like this person is trying to achieve more or less what we want to: https://github.com/vitest-dev/vitest/issues/586#issuecomment-1396966245

**Comment by arboleya** [comment]
@camsjams @Dhaiwat10 Yes, I agree that testing is delicate and that we should move on with #728 for now, which I'm working to unblock. That doesn't mean we can't talk about options here — btw, great set of links, guys. Thanks.

**Comment by danielbate** [comment]
Currently looking at implementing Vitest in #1310 and it is very quick compared to jest.
> Duration 16.38s (transform 4.31s, setup 2.02s, collect 96.78s, tests 31.68s, environment 25ms, prepare 15.15s)

Still facing various issues with the browser implementation however that shouldn't stop us from using it for node environment tests if we wanted to.

**Comment by danielbate** [comment]
Given the performance updates and minimal interruption to our current workflows and tooling, we will implement Vitest completely for our node environment tests, and also add support for a browser test however this will not yet run in CI.

**Comment by arboleya** [comment]
@danielbate Am I tripping, or we're about to become 7.5x times faster (>10mins in CI) by moving to Vitest? ⚡🔥🤘 

@camsjams I believe the above settles the [matter](https://github.com/FuelLabs/fuels-ts/issues/813#issuecomment-1466456300). 😆

**Comment by arboleya** [comment]
Completed via https://github.com/FuelLabs/fuels-ts/pull/1310
