### ISSUE TITLE
Convert a message signed by a wallet into a B512 type

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-ts#826]
### Motivation

When signing a message with a wallet a long `string` type is created.
To be able to recover the user address that has signed the message we need the type to be converted into a `B512` so that it can be recovered in Sway.

### Usage example

```typescript
const signature = "0x0abc...";
const b512 = B512.new(signature);
console.log(b512);

{
  bytes: ["abcd...", "efgh..."]
}
```

**Comment by luizstacio** [comment]
If your contract has an input type B512, it should already work. You should be able to pass as a string.
The coder for this is here: https://github.com/FuelLabs/fuels-ts/blob/master/packages/abi-coder/src/coders/b512.ts
Also, we have an example here on how to use that: https://github.com/FuelLabs/fuels-ts/blob/master/packages/predicate/src/predicate.test.ts
Maybe is a Type issue only?

**Comment by luizstacio** [comment]
@Braqzen the support is broken;

The error is on the b512 encoder and also on the typegen generator. Both expect a type `b512` on the abi.json instead of `struct B512`.

The examples sent are correctly working because the abi is manually inputted and not using the generated ones from the build process.

**Comment by Braqzen** [comment]
> If your contract has an input type B512, it should already work. You should be able to pass as a string. The coder for this is here: https://github.com/FuelLabs/fuels-ts/blob/master/packages/abi-coder/src/coders/b512.ts Also, we have an example here on how to use that: https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/doc-examples.test.ts Maybe is a TypeScript issue only?

I have a struct in Sway which has a field that is `B512`. My custom struct is one of the arguments that is passed into a function call on the contract.
Trying to assign to a type (as seen below) will not work without this conversion so I believe we need a new method as `encode` returns a `uint8array` and that is not what I need for Sway.

```typescript
const [signatures, setSignatures] = useState<SignatureInfoInput[]>([{ 
    message_format: { None: [] }, 
    message_prefix: { None: [] }, 
    signature: { bytes: ["", ""] }, 
    wallet_type: { Fuel: [] }
}])
```

**Comment by Dhaiwat10** [comment]
@luizstacio I looked into the code, and while you said about the coder expecting a wrong type is indeed true - the solution for this issue seems to be unrelated. To solve this particular problem, I think we just need a utility function that would take a hash and output an object with the same shape as `B512`, as shown in the issue description. 

I can file a separate issue for the issue with the coder. Thanks for pointing that out!

**Comment by luizstacio** [comment]
@Dhaiwat10 the current `b512` coder already does all the work to get the string and pass it to the contract as a `{ bytes:[b256, b256] }`. The issue is just that the type b512 not exists anymore the correct matching name is `struct B512`.

You can take a look at the `Option` and `Vec` coders they work with more complex type matching. https://github.dev/FuelLabs/fuels-ts/blob/dd7b1cab0e7c4a5234383ce6fc34f041ee6d03a9/packages/abi-coder/src/constants.ts#L2

**Comment by luizstacio** [comment]
@Dhaiwat10 I think it is not unrelated. The idea here is that `b512` is the correct type, and it should work like a string. Adding a utility can solve the problem, but it would be, in my opinion, the wrong solution as the coder is there for this.

You can look at the `Option` and `Vec`coders. They work with more complex type matching and have some abstractions to improve the DX keeping the API simple.
https://github.dev/FuelLabs/fuels-ts/blob/dd7b1cab0e7c4a5234383ce6fc34f041ee6d03a9/packages/abi-coder/src/constants.ts#L2
