### ISSUE TITLE
Investigate and adopt eslint rule `require-await`

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#832]
### Motivation

If we added an eslint rule like:
https://eslint.org/docs/latest/rules/require-await

It probably would have prevented #705 from occuring.

### Usage example

Update eslintrc, determine how bad things are in relation to required changes. We might discover secret bugs

### Possible implementations

I also looked at and use https://github.com/eslint-community/eslint-plugin-promise a bunch, but this linter didn't pick up on this particular mistake.

Relates to issue #705 and fix #831

**Comment by Torres-ssf** [comment]
I have added the  Eslint rule and investigated the current situation.

Most errors that exist today are test cases created with `async` function but do not use make use of `await` in the test code. 

But there are some functions/class methods declared as `async` which do not make use of `await`. The problem is, most of these cases do not even use or call any function that returns a promise. Some examples are:

1. https://github.com/FuelLabs/fuels-ts/blob/9831e3eb91b62fd9369de06c37fcaf6eaeffbf36/packages/wallet/src/base-unlocked-wallet.ts#L47-L63
2. https://github.com/FuelLabs/fuels-ts/blob/9831e3eb91b62fd9369de06c37fcaf6eaeffbf36/packages/providers/src/provider.ts#L250-L255

3. https://github.com/FuelLabs/fuels-ts/blob/9831e3eb91b62fd9369de06c37fcaf6eaeffbf36/packages/wallet-manager/src/wallet-manager.ts#L186-L194
4. https://github.com/FuelLabs/fuels-ts/blob/9831e3eb91b62fd9369de06c37fcaf6eaeffbf36/packages/wallet-manager/src/storages/memory-storage.ts#L3-L22

It's unclear to me if all of them need to be `async`. Do you know if any of these cases do not need to be `async`? (e.g. `getNetwork`)

And if there are others that we need to fix the inner functions being called? (e.g. `signMessage` and `signTransaction`)

>cc @FuelLabs/sdk-ts

**Comment by Dhaiwat10** [comment]
@Torres-ssf even if these functions don't _actually_ do any asynchronous work right now, I would assume that as long as we `await` them everywhere properly nothing should break.

**Comment by arboleya** [comment]
As Cameron said, these nomenclatures suggest `async` logic, which could require a considerable about of refactoring if we go without it, and then it becomes async later.

@luizstacio I'd guess you did some of these — something to add here?
